name: test_flutter
description: "A new Flutter project."
publish_to: 'none'


environment:
  sdk: ^3.5.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.1.0
  provider: ^6.1.2
  flutter_spinkit: ^5.2.1
  flutter_markdown: ^0.7.3+1
  image_picker: ^1.1.2
  hive_flutter: ^1.1.0
  google_generative_ai: ^0.4.4
  uuid: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.12
  flutter_lints: ^4.0.0
flutter:

  uses-material-design: true

